---
spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: webshow
            client-secret: ${S2S_KEY:AAAAAAAAAAAAAAAA}
test:
  url: ${TEST_URL:http://localhost:8080}
idam:
  api:
    url: ${IDAM_API_BASE_URI:https://idam-api.aat.platform.hmcts.net}
  client:
    id: ${OAUTH_CLIENT_ID:webshow}
    secret: ${IDAM_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: ${IDAM_REDIRECT_URI:https://em-hrs-api-aat.service.core-compute-aat.internal/oauth2/callback}
    grant_type: 'password'
    scope: 'openid roles profile'
s2s:
  api:
    url: ${S2S_BASE_URI:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${FUNCTIONAL_TEST_CLIENT_S2S_TOKEN:AAAAAAAAAAAAAAAA}
    serviceName: ${S2S_SERVICE_NAME:em_gw}
    ccdGwSecret: ${FUNCTIONAL_TEST_CCD_GW_SERVICE_SECRET:AAAAAAAAAAAAAAAA}
    ccdGwServiceName: ${CCD_GW_SERVICE_NAME:ccd_gw}
toggle:
  enable_metadata_endpoint: ${ENABLE_METADATA_ENDPOINT:false}

ccd-def:
  api:
    url: 'http://localhost:4451'

document_management:
  url: 'http://localhost:4603'

core_case_data:
  api:
    url: 'http://localhost:4452'

oidc:
  issuer: ${OIDC_ISSUER_BASE_URI:http://localhost:8080/openam/oauth2/hmcts}

endpoint:
  deleteCase:
    enabled: true
