package uk.gov.hmcts.reform.em.hrs.domain;

public enum AuditActions {

    SHARE_GRANT_OK,
    SHARE_GRANT_FAIL,

    //    SHARE_REVOKE_OK, // REVOCATION NOT DEVELOPED YET
    //    SHARE_REVOKE_FAIL, // REVOCATION NOT DEVELOPED YET

    NOTIFY_OK,
    NOTIFY_FAIL,

    USER_DOWNLOAD_REQUESTED,
    USER_DOWNLOAD_OK,
    USER_DOWNLOAD_UNAUTHORIZED,
    USER_DOWNLOAD_FAIL,


    //    DATA_LIFECYCLE_CREATED, // LIFECYCLE CHANGES NOT DEVELOPED YET
    //    DATA_LIFECYCLE_UPDATED, // LIFECYCLE CHANGES NOT DEVELOPED YET
    //    DATA_LIFECYCLE_DELETED, // LIFECYCLE CHANGES NOT DEVELOPED YET
    //    DATA_LIFECYCLE_HARD_DELETED, // LIFECYCLE CHANGES NOT DEVELOPED YET
    //
    //    TTL_UPDATED_OK, //TTL MECHANISM LIKELY TO BE REPLACED BY EXTERNAL RETAIN/DISPOSE MECHANISM FOR A DELETION
    //    TTL_UPDATED_FAIL //IN WHICH CASE THIS SHOULD BE UPDATED TO SOMETHING LIKE DISPOSE_REQUEST_RECIEVED, SUCCESS+FAIL

}
